version: '3'
services:
  zenn:
    container_name: zenn
    build:
      context: ./docker/zenn
    volumes:
      - ./articles:/zenn/articles
      - ./books:/zenn/books
    working_dir: /zenn
    ports:
      - 8000:8000
